version: '3.6'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine

  celery:
    build: .
    command: celery -A stalker worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  web:
    build: .
    command: python /code/manage.py migrate --noinput
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=changemeinprod
      - CELERY_BROKER_URL=redis://redis:6379
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
