# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-31 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalker', '0002_auto_20180331_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
