# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-23 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stalker', '0003_match_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Grappler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='clip',
            name='grappler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stalker.Grappler'),
        ),
    ]
