# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-25 10:32
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('stalker', '0004_auto_20180523_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
