# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-17 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalker', '0005_clip_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='grappler',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
    ]
