# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-07 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalker', '0006_grappler_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='opponenent',
            field=models.CharField(default='', max_length=250),
        ),
    ]
