# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-20 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stalker', '0008_clip_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clip',
            old_name='opponenent',
            new_name='opponent',
        ),
    ]
